spring.application.name=task-manager
server.port=54455
spring.datasource.url=jdbc:postgresql://localhost:5432/non_existing_db
spring.datasource.username=taskman1
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# Disable Hibernate usage of JDBC metadata
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
# Specify explicitly the dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Database initialization should typically be performed outside of Spring lifecycle
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
# security
security.jwt.tokenExpirationTime=3600
security.jwt.refreshTokenExpirationTime=2592000
security.jwt.secretkey = ovuU7ZvmYCddAEbSN6+oA/512g4R7K1nbbCd1N+3DUpKx6LVU77MaZBtuXtc0HvOgrHneQYvOwEK4WGGEtPERg==
# logs
logging.level.root=INFO
logging.level.com.sergeev.conscious_citizen_server=DEBUG
logging.level.org.springframework.security=DEBUG
# swagger
management.endpoints.web.exposure.include=health, info, metrics
management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ADMIN
management.info.build.enabled=true
management.info.env.enabled=true
management.info.java.enabled=true
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
# media
app.media.storage-root=media_storage
app.media.download-base=/api/media
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# resilience4j
resilience4j.retry.instances.fileStorageRetry.max-attempts=3
resilience4j.retry.instances.fileStorageRetry.wait-duration=50ms
resilience4j.retry.instances.fileStorageRetry.retry-exceptions=java.io.IOException
resilience4j.timelimiter.instances.fileStorageTimeLimiter.timeout-duration=500ms
resilience4j.circuitbreaker.instances.fileStorageCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.fileStorageCircuitBreaker.wait-duration-in-open-state=1s
resilience4j.circuitbreaker.instances.fileStorageCircuitBreaker.record-exceptions=java.io.IOException
#mail
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=conscious-citizen2026@yandex.ru
spring.mail.password=ptjbkcedaqjmntxr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=conscious-citizen2026@yandex.ru
app.frontend.url=http://localhost:5173
#modulith
spring.modulith.events.jdbc.schema-initialization.enabled=true